const state={token:localStorage.getItem('sgtcp_token')||'',user:null,requirements:[],users:[],charts:{}};
const API=(window.SGTCP_CONFIG?.apiBaseUrl||'').replace(/\/$/,'');
const $=id=>document.getElementById(id);
const managerRoles=new Set(['Administrador','Jefa de Unidad','Jefe de Departamento']);

async function api(path,options={}){
  if(!API) throw new Error('Backend pendiente de configuración');
  const headers={'Content-Type':'application/json',...(options.headers||{})};
  if(state.token) headers.Authorization=`Bearer ${state.token}`;
  const res=await fetch(`${API}${path}`,{...options,headers});
  let data=null; try{data=await res.json()}catch{}
  if(!res.ok) throw new Error(data?.detail||'No fue posible completar la operación');
  return data;
}
function toast(message){const n=$('toast');n.textContent=message;n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),2600)}
function setView(name){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));$(`${name}View`)?.classList.remove('hidden');document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name));if(name==='users')loadUsers();}
function badge(value){const key=value==='Terminado'?'green':value==='En ejecución'?'blue':value==='Pendiente'?'orange':'red';return `<span class="badge ${key}">${value||'Sin estado'}</span>`}
function formatDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?v:d.toLocaleString('es-CL',{dateStyle:'short',timeStyle:'short'})}
function isOverdue(r){return r.compromiso&&r.estado!=='Terminado'&&new Date(r.compromiso)<new Date(new Date().toDateString())}

async function login(e){e.preventDefault();$('loginError').textContent='';try{const data=await api('/api/login',{method:'POST',body:JSON.stringify({usuario:$('loginUser').value.trim(),password:$('loginPassword').value})});state.token=data.token;state.user=data.usuario;localStorage.setItem('sgtcp_token',state.token);showApp();await loadAll()}catch(err){$('loginError').textContent=err.message}}
async function restore(){if(!state.token)return;try{state.user=await api('/api/me');showApp();await loadAll()}catch{logout()}}
function showApp(){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');$('accountName').textContent=state.user.nombre;$('accountRole').textContent=state.user.rol;const canManage=managerRoles.has(state.user.rol);$('usersNav').classList.toggle('hidden',!canManage);$('newReqBtn').classList.toggle('hidden',!canManage);$('newReqBtn2').classList.toggle('hidden',!canManage)}
function logout(){state.token='';state.user=null;localStorage.removeItem('sgtcp_token');$('appView').classList.add('hidden');$('loginView').classList.remove('hidden');$('loginPassword').value=''}
async function loadAll(){await Promise.all([loadRequirements(),managerRoles.has(state.user.rol)?loadUsers():Promise.resolve()]);renderDashboard();renderRequirements()}
async function loadRequirements(){state.requirements=await api('/api/requirements')}
async function loadUsers(){if(!managerRoles.has(state.user?.rol))return;state.users=await api('/api/users');renderUsers();fillResponsible()}

function renderDashboard(){const rs=state.requirements;const active=rs.filter(r=>r.estado!=='Terminado');const values=[['Activos',active.length,'Requerimientos abiertos'],['En ejecución',rs.filter(r=>r.estado==='En ejecución').length,'Gestión activa'],['Pendientes',rs.filter(r=>r.estado==='Pendiente').length,'Por iniciar'],['Terminados',rs.filter(r=>r.estado==='Terminado').length,'Cerrados'],['Vencidos',rs.filter(isOverdue).length,'Requieren atención']];$('kpis').innerHTML=values.map(x=>`<article class="kpi"><span>${x[0]}</span><strong>${x[1]}</strong><small>${x[2]}</small></article>`).join('');renderCharts();const attention=active.filter(r=>isOverdue(r)||r.prioridad==='Alta').slice(0,8);$('attentionList').innerHTML=attention.length?attention.map(r=>`<div class="attention-item"><b>REQ-${String(r.id).padStart(3,'0')}</b><div><b>${r.titulo}</b><span>${r.responsable||'Sin responsable'} · ${r.prioridad}</span></div>${isOverdue(r)?'<span class="badge red">Vencido</span>':badge(r.estado)}</div>`).join(''):'<p class="muted">No existen requerimientos críticos.</p>'}
function renderCharts(){const labels=['Pendiente','En ejecución','En espera','Terminado'];const data=labels.map(s=>state.requirements.filter(r=>r.estado===s).length);state.charts.state?.destroy();state.charts.state=new Chart($('stateChart'),{type:'doughnut',data:{labels,datasets:[{data,backgroundColor:['#ff8a1f','#087dcc','#805ad5','#20a548'],borderWidth:0}]},options:{plugins:{legend:{position:'bottom'}},cutout:'68%'}});const executives=state.users.filter(u=>u.rol==='Ejecutivo');const counts=executives.map(u=>state.requirements.filter(r=>r.responsable===u.usuario&&r.estado!=='Terminado').length);state.charts.work?.destroy();state.charts.work=new Chart($('workloadChart'),{type:'bar',data:{labels:executives.map(u=>u.nombre.split(' ').slice(0,2).join(' ')),datasets:[{label:'Activos',data:counts,backgroundColor:'#087dcc',borderRadius:8}]},options:{indexAxis:'y',plugins:{legend:{display:false}},scales:{x:{beginAtZero:true,ticks:{precision:0}},y:{grid:{display:false}}}}})}
function renderRequirements(){const q=$('searchInput')?.value.toLowerCase()||'';const f=$('stateFilter')?.value||'';const rows=state.requirements.filter(r=>(!f||r.estado===f)&&(!q||`${r.id} ${r.titulo} ${r.responsable}`.toLowerCase().includes(q)));$('requirementsBody').innerHTML=rows.map(r=>`<tr><td>REQ-${String(r.id).padStart(3,'0')}</td><td><b>${r.titulo}</b><br><span class="muted">${r.descripcion||''}</span></td><td>${r.responsable||'—'}</td><td>${badge(r.estado)}</td><td>${r.prioridad}</td><td><div class="progress"><i style="width:${r.avance||0}%"></i></div><small>${r.avance||0}%</small></td><td>${formatDate(r.actualizado)}</td></tr>`).join('')}
function renderUsers(){$('usersBody').innerHTML=state.users.map(u=>`<tr><td><b>${u.nombre}</b></td><td>${u.usuario}</td><td>${u.rol}</td><td>${u.email||'—'}</td><td>${u.activo?'<span class="badge green">Activo</span>':'<span class="badge red">Inactivo</span>'}</td></tr>`).join('')}
function fillResponsible(){const users=state.users.filter(u=>u.rol==='Ejecutivo'&&u.activo);$('reqResponsible').innerHTML=users.map(u=>`<option value="${u.usuario}">${u.nombre}</option>`).join('')}
async function createRequirement(e){e.preventDefault();try{await api('/api/requirements',{method:'POST',body:JSON.stringify({titulo:$('reqTitle').value.trim(),descripcion:$('reqDescription').value.trim(),responsable:$('reqResponsible').value,prioridad:$('reqPriority').value,compromiso:$('reqDue').value,estado:'Pendiente',avance:0})});$('requirementDialog').close();e.target.reset();await loadRequirements();renderDashboard();renderRequirements();toast('Requerimiento registrado en Google Sheets')}catch(err){toast(err.message)}}
async function createUser(e){e.preventDefault();try{await api('/api/users',{method:'POST',body:JSON.stringify({nombre:$('userName').value.trim(),usuario:$('userLogin').value.trim(),email:$('userEmail').value.trim(),rol:$('userRole').value,password:$('userPassword').value})});$('userDialog').close();e.target.reset();await loadUsers();renderDashboard();toast('Usuario creado correctamente')}catch(err){toast(err.message)}}

document.addEventListener('DOMContentLoaded',()=>{$('loginForm').addEventListener('submit',login);$('logoutBtn').addEventListener('click',logout);document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',()=>setView(x.dataset.view)));[$('newReqBtn'),$('newReqBtn2')].forEach(x=>x?.addEventListener('click',()=>$('requirementDialog').showModal()));$('newUserBtn')?.addEventListener('click',()=>$('userDialog').showModal());document.querySelectorAll('[data-close]').forEach(x=>x.addEventListener('click',()=>$(x.dataset.close).close()));$('requirementForm').addEventListener('submit',createRequirement);$('userForm').addEventListener('submit',createUser);$('searchInput').addEventListener('input',renderRequirements);$('stateFilter').addEventListener('change',renderRequirements);if(!API){$('loginError').innerHTML='<div class="status-note">La interfaz V2 está activa. Falta configurar <b>api_base_url</b> en los Secrets de Streamlit para conectar el backend de producción.</div>'}restore()});