/* SGTCP 3.2 · Estabilización UX, seguridad y guardado optimista */
(function(){
'use strict';if(typeof state==='undefined')return;const pending=new Map();
window.esc=function(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))};
const safePct=v=>Math.max(0,Math.min(100,Number(v)||0));
function ensureDialog(){if(document.getElementById('sgtcpActionDialog'))return;const d=document.createElement('dialog');d.id='sgtcpActionDialog';d.innerHTML='<div class="dialog-shell"><div class="dialog-head"><div><p class="eyebrow">Confirmación</p><h3 id="sgtcpActionTitle">Confirmar acción</h3></div></div><div id="sgtcpActionMessage" style="white-space:pre-line;line-height:1.55;margin:12px 0 18px"></div><label id="sgtcpPromptWrap" class="hidden">Información<input id="sgtcpPromptInput" autocomplete="off"></label><div class="dialog-actions"><button id="sgtcpActionCancel" class="btn ghost" type="button">Cancelar</button><button id="sgtcpActionOk" class="btn primary" type="button">Confirmar</button></div></div>';document.body.appendChild(d)}
function actionDialog({title='Confirmar acción',message='',prompt=false,initial='',ok='Confirmar',danger=false,inputType='text'}={}){ensureDialog();const d=document.getElementById('sgtcpActionDialog'),t=document.getElementById('sgtcpActionTitle'),m=document.getElementById('sgtcpActionMessage'),w=document.getElementById('sgtcpPromptWrap'),i=document.getElementById('sgtcpPromptInput'),yes=document.getElementById('sgtcpActionOk'),no=document.getElementById('sgtcpActionCancel');t.textContent=title;m.textContent=message;w.classList.toggle('hidden',!prompt);i.value=initial;i.type=inputType;yes.textContent=ok;yes.className=danger?'btn danger':'btn primary';return new Promise(resolve=>{const done=v=>{yes.onclick=null;no.onclick=null;d.oncancel=null;d.close();resolve(v)};yes.onclick=()=>done(prompt?i.value:true);no.onclick=()=>done(prompt?null:false);d.oncancel=e=>{e.preventDefault();done(prompt?null:false)};d.showModal();if(prompt)setTimeout(()=>i.focus(),30)})}
window.sgtcpConfirm=(message,title='Confirmar acción',ok='Confirmar',danger=false)=>actionDialog({title,message,ok,danger});window.sgtcpPrompt=(message,initial='',title='Información requerida',inputType='text')=>actionDialog({title,message,prompt:true,initial,ok:'Continuar',inputType});
window.login=async function(e){e.preventDefault();document.getElementById('loginError').textContent='';const b=e.submitter;if(b)b.disabled=true;try{const password=document.getElementById('loginPassword').value,d=await call('login',{usuario:document.getElementById('loginUser').value.trim(),password});state.session=d.session;state.user=d.usuario;localStorage.setItem('sgtcp_session',state.session);if(d.cambiar_password){const n=await sgtcpPrompt('Primer ingreso: cree una nueva contraseña de al menos 10 caracteres.','','Crear nueva contraseña','password');if(!n||n.length<10)throw new Error('Debe definir una contraseña de al menos 10 caracteres.');await call('cambiar_password',{actual:password,nueva:n})}await loadAll();showApp()}catch(err){document.getElementById('loginError').textContent=err.message}finally{if(b)b.disabled=false}};
window.saveUpdate=async function(){const r=state.requirements.find(x=>Number(x.id)===Number(state.selectedId));if(!r)return toast('Requerimiento no encontrado.','error');if(r.estado==='Terminado')return toast('El requerimiento terminado está bloqueado.','error');const detail=document.getElementById('detailUpdate')?.value.trim()||'';if(!detail)return toast('Ingrese una actualización para dejar trazabilidad.','error');if(pending.has(Number(r.id)))return toast('Este requerimiento ya se está sincronizando.','info');const changes={estado:document.getElementById('detailStatus').value,avance:safePct(document.getElementById('detailProgress').value)};if(typeof manager==='function'&&manager()){changes.prioridad=document.getElementById('detailPriority').value;changes.descripcion=document.getElementById('detailDescription').value.trim()}if(changes.estado==='Terminado')changes.avance=100;const ok=await sgtcpConfirm(`REQ-${String(r.id).padStart(3,'0')} · ${r.titulo}\n\nEstado: ${r.estado} → ${changes.estado}\nAvance: ${safePct(r.avance)}% → ${changes.avance}%\n\nLa actualización quedará registrada permanentemente en la trazabilidad.`,'Guardar actualización','Guardar');if(!ok)return;const snapshot={...r};Object.assign(r,changes,{actualizado:new Date().toISOString()});document.getElementById('detailUpdate').value='';try{renderRequirements();renderRecent();renderAlerts();if(typeof renderAttention==='function')renderAttention()}catch(_){}document.getElementById('detailDialog')?.close();toast('Actualización visible · sincronizando con Google Sheets…','success');const task=call('actualizar_req',{id:r.id,cambios:changes,detalle:detail});pending.set(Number(r.id),task);try{await task;toast('✓ Actualización guardada y trazabilidad sincronizada.','success')}catch(err){Object.keys(r).forEach(k=>delete r[k]);Object.assign(r,snapshot);if(typeof renderAll==='function')renderAll();toast(`No se pudo guardar. El cambio fue revertido: ${err.message}`,'error')}finally{pending.delete(Number(r.id))}};
window.logout=async function(){const ok=await sgtcpConfirm('La sesión actual se cerrará y volverá a la pantalla de ingreso.','Cerrar sesión','Cerrar sesión');if(!ok)return;try{if(state.session)await call('logout')}catch(_){}finally{clearSession()}};
const oldCreate=window.createRequirement;window.createRequirement=async function(e){e.preventDefault();const req={titulo:document.getElementById('reqTitle').value.trim(),descripcion:document.getElementById('reqDescription').value.trim(),responsable:document.getElementById('reqResponsible').value,prioridad:document.getElementById('reqPriority').value,compromiso:document.getElementById('reqDue').value};if(!req.responsable)return toast('Seleccione un responsable.','error');const ok=await sgtcpConfirm(`${req.titulo}\n\nResponsable: ${userName(req.responsable)}\nPrioridad: ${req.prioridad}\n\nEl ejecutivo recibirá el requerimiento en su cartera.`,'Registrar requerimiento','Registrar');if(!ok)return;const b=e.submitter;if(b)b.disabled=true;try{await call('crear_req',{req});document.getElementById('requirementDialog').close();e.target.reset();await loadAll();toast('✓ Requerimiento creado y asignado correctamente.','success')}catch(err){toast(err.message,'error')}finally{if(b)b.disabled=false}};
function bind(){ensureDialog();const lf=document.getElementById('loginForm');if(lf)lf.onsubmit=window.login;const s=document.getElementById('saveUpdateBtn');if(s)s.onclick=window.saveUpdate;const l=document.getElementById('logoutBtn');if(l)l.onclick=window.logout;const f=document.getElementById('requirementForm');if(f)f.onsubmit=window.createRequirement}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(bind,0));else setTimeout(bind,0);
})();