/* SGTCP 3.2 · Sincronización inteligente optimizada */
(function(){
'use strict';
if(typeof state==='undefined'||typeof call!=='function')return;
const SYNC_INTERVAL=45000,RESUME_DEBOUNCE=2500;let timer=null,syncing=false,initialized=false,resumeTimer=null;state.syncAlerts=Array.isArray(state.syncAlerts)?state.syncAlerts:[];
const isExecutive=()=>state.user?.rol==='Ejecutivo',isBusy=()=>document.hidden||!state.session||!!document.querySelector('dialog[open]'),idOf=r=>Number(r?.id)||0;
const reqSignature=r=>[idOf(r),String(r?.responsable||''),String(r?.estado||''),Number(r?.avance)||0,String(r?.prioridad||''),String(r?.actualizado||''),String(r?.titulo||'')].join('|');
const userSignature=u=>[String(u?.usuario||''),String(u?.nombre||''),String(u?.rol||''),String(u?.email||''),u?.activo?'1':'0'].join('|');
function mapById(rows){const m=new Map();(rows||[]).forEach(r=>m.set(idOf(r),r));return m}
function requirementsChanged(a,b){if((a||[]).length!==(b||[]).length)return true;const old=mapById(a);return(b||[]).some(r=>reqSignature(old.get(idOf(r)))!==reqSignature(r))}
function usersChanged(a,b){if((a||[]).length!==(b||[]).length)return true;const old=new Map((a||[]).map(u=>[String(u.usuario),userSignature(u)]));return(b||[]).some(u=>old.get(String(u.usuario))!==userSignature(u))}
function currentView(){const active=[...document.querySelectorAll('.view')].find(v=>!v.classList.contains('hidden'));return active?.id?.replace(/View$/,'')||'dashboard'}
function addSyncAlert(r,type='Nueva asignación'){const id=idOf(r);if(!id)return;const key=`${type}:${id}`;if(state.syncAlerts.some(a=>a.key===key))return;state.syncAlerts.unshift({key,id,type,titulo:String(r.titulo||''),fecha:new Date().toISOString()});if(state.syncAlerts.length>30)state.syncAlerts.length=30;try{sessionStorage.setItem('sgtcp_sync_alerts',JSON.stringify(state.syncAlerts))}catch(_){}}
function restoreAlerts(){try{const raw=sessionStorage.getItem('sgtcp_sync_alerts'),rows=raw?JSON.parse(raw):[];if(Array.isArray(rows))state.syncAlerts=rows}catch(_){}}
function removeAlertsFor(id){const n=Number(id)||0;state.syncAlerts=state.syncAlerts.filter(a=>Number(a.id)!==n);try{sessionStorage.setItem('sgtcp_sync_alerts',JSON.stringify(state.syncAlerts))}catch(_){}}
const baseRenderAlerts=window.renderAlerts;
window.renderAlerts=function(){if(typeof baseRenderAlerts==='function')baseRenderAlerts();const page=document.getElementById('alertsPage'),count=document.getElementById('navAlertCount');if(!page)return;const pending=(state.syncAlerts||[]).filter(a=>state.requirements.some(r=>idOf(r)===Number(a.id)&&r.estado!=='Terminado'));if(pending.length){const html=pending.map(a=>`<article class="panel alert-card alert-new" style="margin-bottom:10px"><div class="alert-card-main"><div class="attention-icon">${a.type==='Reasignación'?'🔁':'🔔'}</div><div><div class="alert-card-top"><b>REQ-${String(Number(a.id)).padStart(3,'0')} · ${(window.esc||String)(a.titulo)}</b><span class="badge ${a.type==='Reasignación'?'purple':'blue'}">${a.type==='Reasignación'?'REASIGNADO':'NUEVA ASIGNACIÓN'}</span></div><p>${a.type==='Reasignación'?'Este requerimiento fue reasignado a usted y requiere revisión.':'Tiene un nuevo requerimiento asignado y requiere revisión.'}</p></div></div><button class="btn ghost sync-alert-open" data-id="${Number(a.id)}">Revisar ahora</button></article>`).join('');page.insertAdjacentHTML('afterbegin',html);page.querySelectorAll('.sync-alert-open').forEach(b=>b.onclick=()=>openDetail(Number(b.dataset.id)))}if(count){const operational=Number(count.textContent)||0,total=operational+pending.length;count.textContent=total;count.classList.toggle('hidden',total===0)}};
const baseOpenDetail=window.openDetail;window.openDetail=async function(id){removeAlertsFor(id);renderAlerts();return baseOpenDetail(id)};
function detectExecutiveAssignments(oldRows,newRows){if(!isExecutive()||!initialized)return[];const old=mapById(oldRows),notices=[];for(const r of newRows){const id=idOf(r),prev=old.get(id);if(!prev){addSyncAlert(r,'Nueva asignación');notices.push({r,type:'Nueva asignación'});continue}if(String(prev.responsable)!==String(r.responsable)&&String(r.responsable)===String(state.user?.usuario)){addSyncAlert(r,'Reasignación');notices.push({r,type:'Reasignación'})}}return notices}
function renderVisible(reqChanged,userChanged){const view=currentView();try{if(userChanged&&typeof fillSelects==='function')fillSelects();switch(view){case'dashboard':renderDashboard();break;case'requirements':renderRequirements();break;case'team':if(manager())renderTeam();break;case'trace':renderTrace();break;case'alerts':renderAlerts();break;case'indicators':if(manager())renderIndicators();break;case'users':if(manager())renderUsers();break;default:if(reqChanged)renderRequirements()}if(view!=='alerts')renderAlerts()}catch(e){console.warn('SGTCP sync render:',e)}}
const baseSetView=window.setView;window.setView=function(name){baseSetView(name);requestAnimationFrame(()=>{try{if(name==='dashboard')renderDashboard();else if(name==='requirements')renderRequirements();else if(name==='team'&&manager())renderTeam();else if(name==='trace')renderTrace();else if(name==='alerts')renderAlerts();else if(name==='indicators'&&manager())renderIndicators();else if(name==='users'&&manager())renderUsers()}catch(e){console.warn('SGTCP view render:',e)}})};
async function syncNow(reason='interval'){if(syncing||isBusy())return false;syncing=true;try{const previousReq=state.requirements.slice(),previousUsers=state.users.slice(),d=await call('listar'),nextUser=d.data?.usuario||state.user,nextUsers=d.data?.usuarios||[],nextReq=d.data?.requerimientos||[],notices=detectExecutiveAssignments(previousReq,nextReq),reqChanged=requirementsChanged(previousReq,nextReq),userChanged=usersChanged(previousUsers,nextUsers);state.user=nextUser;state.users=nextUsers;state.requirements=nextReq;if(reqChanged||userChanged)renderVisible(reqChanged,userChanged);if(notices.length){const n=notices.length;toast(n===1?`${notices[0].type}: REQ-${String(idOf(notices[0].r)).padStart(3,'0')} · ${notices[0].r.titulo}`:`Tiene ${n} nuevas asignaciones por revisar.`,'success');renderAlerts()}initialized=true;return reqChanged||userChanged}catch(e){if(String(e.message||'').toLowerCase().includes('sesión expiró')){try{clearSession()}catch(_){}}console.warn(`SGTCP sync (${reason}):`,e);return false}finally{syncing=false}}
function schedule(){clearInterval(timer);timer=setInterval(()=>syncNow('interval'),SYNC_INTERVAL)}function resumeSoon(){clearTimeout(resumeTimer);resumeTimer=setTimeout(()=>syncNow('resume'),RESUME_DEBOUNCE)}
restoreAlerts();document.addEventListener('visibilitychange',()=>{if(!document.hidden)resumeSoon()});window.addEventListener('focus',resumeSoon);document.addEventListener('DOMContentLoaded',()=>{initialized=false;setTimeout(()=>{if(state.session){initialized=true;renderAlerts()}},2200);schedule()});window.SGTCP_SYNC={syncNow,interval:SYNC_INTERVAL};
})();